#!/usr/bin/env python2
import os
import argparse

BTHEMER_FOLDER = os.path.expanduser('~/.bthemer')

def remove_extension(x):
    return x.rsplit('.', 1)[0]


def get_themes():
    return map(remove_extension,
               os.listdir(BTHEMER_FOLDER+'/themes'))

def list_themes():
    print '\n'.join(get_themes())

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser('list')
    args = parser.parse_args()
    if args.command == "list":
        list_themes()
    elif args.command == "apply"
