#!/bin/bash
. ~/.bin/lemonbar_config
while read input;
do
    case $input in
	"WIFI")
	    terminator -e nmtui &
	    ;;
	"SHUTUP")
	    pactl set-sink-mute 1 toggle
	    ;;
	"VOL"*)
	    TEST="$(echo $input | awk '{print $2}' )"
	    ~/.bin/volume.sh set $TEST
	    ;;
	"BATTERY")
	    [[ $(< $BATTERYFILE) -eq 0 ]] && echo -n 1 > $BATTERYFILE || echo -n 0 > $BATTERYFILE

	    ;;
	"TOGGLEVOLUME")
	    [[ $(< $FILE) -eq 0 ]] && echo -n 1 > $FILE || echo -n 0 > $FILE
	    ;;
	"TOGGLEWIFI")
	    [[ $(< $WIFIFILE) -eq 0 ]] && echo -n 1 > $WIFIFILE || echo -n 0 > $WIFIFILE
	    
    esac
done
