#!/bin/bash
. ~/.bin/lemonbar_config
OPEN=true


battery() {
    BATTERY="$(awk "{print}" /sys/class/power_supply/BAT0/capacity)"
    BATTERY_ICON=" "
    if [[ $BATTERY -ge 90 ]];
    then
	BATTERY_ICON="\uf240"
    elif [[ "$BATTERY" -ge 70 ]];
    then
	BATTERY_ICON="\uf241"
    elif [[ "$BATTERY" -ge 30 ]];
    then
	BATTERY_ICON="\uf242"
    elif [[ "$BATTERY" -ge 10 ]];
    then
	BATTERY_ICON="\uf243"
    else
	BATTERY_ICON="\uf244"
    fi
    echo -e "$BATTERY_ICON  $BATTERY%"
}

clock() {
    CLOCK="$(date +"%R")"
    DATE="$(date +"%d/%m/%Y")"
    echo -e "\uf073 "$DATE"    \uf017" $CLOCK
}

wifi(){
    WIFISTATE="$(cat $WIFIFILE)"
    WIFI="%{A:TOGGLEWIFI:}%{A3:WIFI:}%{B#11ffffff}$PADDING\uf1eb  "
    if [ "$WIFISTATE" -eq 0 ]
    then
	INFO="$(awk "NR==3 {print int((\$3/70)*100)}" /proc/net/wireless)%"
    else
	INFO="$(iwgetid -r)"
    fi
    echo $WIFI" "$INFO"$PADDING%{B#00000000}%{A}%{A}"
}

volume(){
    VOLUME="$(amixer get Master | awk -F'[]%[]' '/%/ {if ($5 == "off") {printf "%d\n",0} else {printf "%d\n", $2}}' |uniq)"
    VOLUMECOMMAND="VOL"
    STATE="$(cat $FILE)"
    VOLUMEBAR="%{A3:SHUTUP:}%{A:TOGGLEVOLUME:}"
    if [ "$VOLUME" -eq 0 ]
    then
	VOLUMEBAR=$VOLUMEBAR"\uf026%{A} "
    else
	VOLUMEBAR=$VOLUMEBAR"\uf028%{A} "
    fi
    if [ "$STATE" -eq 0 ]
    then
	for i in {1..20} 
	do
	    if [ $((i*5)) -le "$VOLUME" ];
	    then
		VOLUMEBAR=$VOLUMEBAR"%{A:"$VOLUMECOMMAND" "$((i*5))":}━%{A}"
	    else
		VOLUMEBAR=$VOLUMEBAR"%{A:"$VOLUMECOMMAND" "$((i*5))":}─%{A}"
	    fi
	    VOLUMEBAR=$VOLUMEBAR
	done
    fi
    echo "$VOLUMEBAR $VOLUME%{A}"
}


PADDING="  "


while true; do
    BAR_INPUT="$(wifi)      %{B#11ffffff}$PADDING$(volume)$PADDING%{B#00000000}%{r}%{B#11ffffff}$PADDING%{A:BATTERY:}$(battery)%{A}$PADDING%{B#00000000}      %{B#11ffffff}$PADDING%{A:CLOSE:}$(clock)%{A}$PADDING%{B#00000000}"
    echo -e "$BAR_INPUT"
    sleep 0.1s
done
