#!/bin/bash
. ~/.bin/lemonbar_config

#Default states
echo 1 > $FILE
echo 1 > $WIFIFILE
echo 1 > $BATTERYFILE

#Invisible bar to treat lemonbar as a window
conky -c ~/.bin/conky.conf &> /dev/null&

#Top bar
~/.bin/lemonbar_output | lemonbar -p -f $ICON_FONT -g $TOP_POSITION -d  -u "3" -U $BORDER_COLOR -f $TOP_BAR_FONT -F $FONT_COLOR -a 50 | ~/.bin/lemonbar_clicked &

#Bottom workspace bar
~/.bin/bottom_panel_output | lemonbar -p -f $ICON_FONT -g $BOT_POSITION -d -f $BOT_BAR_FONT  -u $WORKSPACE_ICON_SIZE -a 15 -d -F "#000000" -U $FOCUSED_WORKSPACE_COLOR | ~/.bin/change_workspace
