#!/bin/bash



battery() {
    BATTERY="$(awk "{print}" /sys/class/power_supply/BAT0/capacity)"
    BATTERY_ICON=" "
    if [[ $BATTERY -ge 90 ]];
    then
	BATTERY_ICON="\uf240"
    elif [[ "$BATTERY" -ge 70 ]];
    then
	BATTERY_ICON="\uf241"
    elif [[ "$BATTERY" -ge 30 ]];
    then
	BATTERY_ICON="\uf242"
    elif [[ "$BATTERY" -ge 10 ]];
    then
	BATTERY_ICON="\uf243"
    else
	BATTERY_ICON="\uf244"
    fi
    BATTERYSTATE="$(cat $BATTERYFILE)"
    if [ "$BATTERYSTATE" -eq 1 ]
    then
	echo -e "$BATTERY_ICON  $BATTERY%"
    else
	TIME_LEFT="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "time" | sed -e 's/^.*\( [0-9].*\)/\1/g' | sed -e 's/minutes/m/' | sed -e 's/hours/h/')"
	echo -e "$BATTERY_ICON $TIME_LEFT"
    fi
}

clock() {
    CLOCK="$(date +"%R")"
    DATE="$(date +"%d/%m/%Y")"
    echo -e "\uf073 "$DATE"    \uf017" $CLOCK
}

wifi(){
    WIFISTATE="$(cat $WIFIFILE)"
    WIFI="%{A:TOGGLEWIFI:}%{A3:WIFI:}\uf1eb  "
    if [ "$WIFISTATE" -eq 0 ]
    then
	INFO="$(awk "NR==3 {print int((\$3/70)*100)}" /proc/net/wireless)%"
	if [[ "$INFO" = "%" ]]
	then
	    INFO="Not Connected"
	fi
    else
	INFO="$(iwgetid -r)"
	if [[ -z "$INFO" ]]
	then
	    INFO="Not Connected"
	fi
    fi
    echo $WIFI" "$INFO"%{A}%{A}"
}

volume(){
    VOLUME="$(amixer get Master | awk -F'[]%[]' '/%/ {if ($5 == "off") {printf "%d\n",0} else {printf "%d\n", $2}}' |uniq)"
    VOLUMECOMMAND="VOL"
    STATE="$(cat $FILE)"
    VOLUMEBAR="%{A3:SHUTUP:}%{A:TOGGLEVOLUME:}"
    if [ "$VOLUME" -eq 0 ]
    then
	VOLUMEBAR=$VOLUMEBAR"\uf026%{A} "
    else
	VOLUMEBAR=$VOLUMEBAR"\uf028%{A} "
    fi
    if [ "$STATE" -eq 0 ]
    then
	for i in {1..20} 
	do
	    if [ $((i*5)) -le "$VOLUME" ];
	    then
		VOLUMEBAR=$VOLUMEBAR"%{A:"$VOLUMECOMMAND" "$((i*5))":}━%{A}"
	    else
		VOLUMEBAR=$VOLUMEBAR"%{A:"$VOLUMECOMMAND" "$((i*5))":}─%{A}"
	    fi
	    VOLUMEBAR=$VOLUMEBAR
	done
    fi
    echo "$VOLUMEBAR $VOLUME%{A}"
}


PADDING="  "


while true; do
    . ~/.bin/lemonbar_config
    BATTERY="$(awk "{print}" /sys/class/power_supply/BAT0/capacity)"
    TOGGLE=1
    BAR_INPUT="%{F$FONT_COLOR}%{U$BORDER_COLOR}%{c}%{+u}%{+o}%{B$BORDER_COLOR} %{B$BACKGROUND_COLOR}"
    if [ "$BATTERY" -lt 15 ]
    then
	if [ "$(cat $BATTERYTOGGLE)" -eq 1 ] && [ "$(awk "{print}" /sys/class/power_supply/BAT0/status)" == "Discharging" ]
	then
	    BAR_INPUT=$BAR_INPUT"%{R}"
	    echo 0 > $BATTERYTOGGLE
	else
	    echo 1 > $BATTERYTOGGLE
	fi
    fi

    BAR_INPUT=$BAR_INPUT"$PADDING$(wifi)$PADDING"
    BAR_INPUT=$BAR_INPUT"    $PADDING$(volume)$PADDING"
    BAR_INPUT=$BAR_INPUT"    $PADDING$(battery)$PADDING" 
    BAR_INPUT=$BAR_INPUT"    $PADDING$(clock)$PADDING%{B$BORDER_COLOR}%{-u}%{-o} %{B#00000000}"
    echo -e "$BAR_INPUT"
    sleep 1
done
