#!/bin/bash

# Controls volume.
# Usage:
# volume {up | down | set <vol> | show}

if [ "$1" = up ]; then
    pamixer -i 5
elif [ "$1" = "down" ]; then
    pamixer -d 5
elif [ "$1" = "set" ]; then
    pamixer --set-volume "$2"
elif [ "$1" = "toggle" ]; then
    pamixer -t
elif [ "$1" = "show" ]; then
    echo -e "$(pamixer --get-volume)"
fi
