#!/bin/bash

# Toggles unfocused window opacity between 1 and 0.9
# Usage:
# window_opacity


UNFOCUSED_OPACITY=0.9
killall compton
STATE="$(< ~/.config/compton.conf grep inactive | grep -o -e '[0-9]\(.[0-9]\)\?')"
CONDITION="$(echo "${STATE}"==${UNFOCUSED_OPACITY}|bc)"

if [[ $CONDITION -eq 1 ]]
then
    echo "$CONDITION"
    NEW=1
else
    NEW=$UNFOCUSED_OPACITY
fi
sed -i "/inactive-opacity/ c inactive-opacity = ${NEW};" ~/dotfiles/compton.conf
compton -b
